openapi: 3.0.0
info:
  description: CS6650 Fall 2023
  version: "1.0.0"
  title: Album Store API
  contact:
    email: i.gorton@northeasern.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /albums:
    post:
      summary: Returns the new key and size of an image in bytes.
      operationId: newAlbum
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                artist:
                  type: string
                title:
                  type: string
                year:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/imageMetaData'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMsg'

  /albums/{albumID}:
    get:
      summary: get album by key
      operationId: getAlbumByKey
      parameters:
        - name: albumID
          in: path
          description: path  parameter is album key to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: JSON data for album info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/albumInfo'
        '404':
          description: Key not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMsg'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMsg'
components:
  schemas:
    imageMetaData:
      type: object
      properties:
        albumID:
          type: string
        imageSize:
          type: string
    albumInfo:
      type: object
      properties:
        artist:
          type: string
          description: album performers
          example: Sex Pistols
        title:
          type: string
          description: album title
          example: Never Mind The Bollocks!
        year:
          type: string
          description: year released
          example: 1977
    errorMsg:
      type: object
      properties:
        msg:
          type: string

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:8080/AlbumStore